import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ShippingAddress } from './types';

export function AddressPage({ onBack, onSave }: { onBack: () => void; onSave: (address: ShippingAddress) => void }) {
  const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [building,setBuilding]=useState(''); const [line,setLine]=useState(''); const [city,setCity]=useState(''); const [pincode,setPincode]=useState('');
  const save=()=>{if(name.length<2||phone.length!==10||building.length<2||line.length<4||city.length<2||pincode.length!==6)return Alert.alert('Complete your address','Fill all required fields to continue.');onSave({name,phone,line:`${building}, ${line}`,city,pincode});};
  const field=(label:string,value:string,set:(text:string)=>void,icon:keyof typeof Ionicons.glyphMap,options={})=><View style={s.field}><Ionicons name={icon} size={22} color="#3F72E5"/><View style={s.fieldCopy}><Text style={s.label}>{label} <Text style={s.required}>*</Text></Text><TextInput value={value} onChangeText={set} placeholder={`Enter ${label.toLowerCase()}`} placeholderTextColor="#9aa3ab" style={s.input} {...options}/></View></View>;
  return <View style={s.page}><View style={s.header}><Pressable onPress={onBack}><Ionicons name="arrow-back" size={25}/></Pressable><Text style={s.headerTitle}>CHECKOUT</Text><Ionicons name="share-social-outline" size={24} color="#3F72E5"/></View><ScrollView contentContainerStyle={s.content}><View style={s.titleRow}><Text style={s.title}>Add billing address</Text><Text style={s.step}>Step 1 of 2</Text></View><View style={s.rule}/><Text style={s.section}>Contact Details</Text>{field('Full Name',name,setName,'person-outline')}{field('Phone number',phone,setPhone,'call-outline',{keyboardType:'phone-pad',maxLength:10})}<Text style={s.section}>Address Details</Text>{field('House / flat / Building',building,setBuilding,'location-outline')}{field('Area / Street / Locality',line,setLine,'home-outline')}{field('City / Town',city,setCity,'business-outline')}{field('Pincode',pincode,setPincode,'navigate-outline',{keyboardType:'number-pad',maxLength:6})}</ScrollView><Pressable onPress={save} style={s.button}><Text style={s.buttonText}>Continue to payment</Text></Pressable></View>;
}

const s=StyleSheet.create({page:{backgroundColor:'#FFFFFF',flex:1},header:{alignItems:'center',borderBottomColor:'#F5F5F5',borderBottomWidth:1,flexDirection:'row',height:70,justifyContent:'space-between',paddingHorizontal:16},headerTitle:{color:'#3F72E5',fontSize:16,fontWeight:'800'},content:{gap:12,padding:17,paddingBottom:96},titleRow:{flexDirection:'row',justifyContent:'space-between',marginTop:12},title:{color:'#1A1C1D',fontSize:16,fontWeight:'800'},step:{color:'#999',fontSize:12,fontWeight:'700'},rule:{backgroundColor:'#3F72E5',height:2,width:152},section:{color:'#1A1C1D',fontSize:16,fontWeight:'800',marginTop:9},field:{alignItems:'center',backgroundColor:'#FFFFFF',borderColor:'#F5F5F5',borderRadius:6,borderWidth:1,elevation:0,flexDirection:'row',minHeight:56,paddingHorizontal:10},fieldCopy:{flex:1,marginLeft:10},label:{color:'#2C2D2E',fontSize:12,fontWeight:'700'},required:{color:'#3F72E5'},input:{color:'#2C2D2E',fontSize:13,height:27,padding:0},button:{alignItems:'center',backgroundColor:'#3F72E5',borderRadius:8,bottom:20,height:56,justifyContent:'center',left:16,position:'absolute',right:16},buttonText:{color:'#FFFFFF',fontSize:17,fontWeight:'800'}});
