import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ShippingAddress, ShopProduct } from './types';

export function CheckoutPage({ product, quantity, address, onBack, onAddress }: { product: ShopProduct; quantity: number; address: ShippingAddress | null; onBack: () => void; onAddress: () => void }) {
  const total = (Number(product.price.replace(/[^0-9]/g, '')) || 0) * quantity;
  return <View style={s.page}><View style={s.header}><Pressable onPress={onBack}><Ionicons name="arrow-back" size={25} /></Pressable><Text style={s.headerTitle}>CHECKOUT</Text><Ionicons name="share-social-outline" size={24} color="#2B547B" /></View><View style={s.progress}><Text style={s.current}>1  Address</Text><Text style={s.future}>—  2  Payment  —  3  Review</Text></View><Text style={s.title}>Billing Address</Text><Pressable onPress={onAddress} style={s.card}>{address ? <><Text style={s.name}>{address.name}</Text><Text style={s.copy}>{address.line}</Text><Text style={s.copy}>{address.city} - {address.pincode}</Text><Text style={s.copy}>{address.phone}</Text></> : <><Text style={s.muted}>None selected</Text><Text style={s.action}>Add billing address</Text></>}<Ionicons name="chevron-forward" size={22} color="#2B547B" style={s.chevron} /></Pressable><Text style={s.title}>Shipping Address</Text><View style={s.option}><Ionicons name="radio-button-on" size={18} color="#2B547B" /><Text style={s.optionCopy}>same as billing address</Text></View><View style={s.summary}><View style={s.row}><Text style={s.product}>{product.name} ({quantity} item)</Text><Text style={s.value}>₹{total.toLocaleString('en-IN')}</Text></View><View style={s.line}/><View style={s.row}><Text style={s.total}>Total</Text><Text style={s.total}>₹{total.toLocaleString('en-IN')}</Text></View></View><Pressable onPress={onAddress} style={s.button}><Text style={s.buttonText}>{address ? 'Continue to payment' : 'Continue to add address'}</Text></Pressable></View>;
}

const s = StyleSheet.create({ page:{backgroundColor:'#FFFFFF',flex:1,paddingHorizontal:16},header:{alignItems:'center',borderBottomColor:'#F5F5F5',borderBottomWidth:1,flexDirection:'row',height:70,justifyContent:'space-between'},headerTitle:{color:'#3F72E5',fontSize:16,fontWeight:'800'},progress:{alignItems:'center',flexDirection:'row',gap:12,justifyContent:'center',marginVertical:28},current:{color:'#3F72E5',fontSize:12,fontWeight:'800'},future:{color:'#7e8790',fontSize:12,fontWeight:'700'},title:{color:'#1A1C1D',fontSize:16,fontWeight:'800',marginBottom:12},card:{backgroundColor:'#FFFFFF',borderRadius:7,elevation:2,marginBottom:22,minHeight:64,padding:12},muted:{color:'#888',fontSize:12},action:{color:'#3F72E5',fontSize:14,fontWeight:'800',marginTop:5},name:{color:'#1A1C1D',fontSize:15,fontWeight:'800'},copy:{color:'#2C2D2E',fontSize:12,lineHeight:17},chevron:{position:'absolute',right:12,top:21},option:{alignItems:'center',backgroundColor:'#FFFFFF',borderRadius:7,elevation:2,flexDirection:'row',gap:12,height:46,marginBottom:22,paddingHorizontal:12},optionCopy:{color:'#2C2D2E',fontSize:12,fontWeight:'700'},summary:{borderColor:'#F5F5F5',borderRadius:8,borderWidth:1,padding:14},row:{flexDirection:'row',justifyContent:'space-between'},product:{color:'#2C2D2E',flex:1,fontWeight:'700',paddingRight:12},value:{color:'#1A1C1D',fontWeight:'800'},line:{backgroundColor:'#F5F5F5',height:1,marginVertical:13},total:{color:'#1A1C1D',fontSize:18,fontWeight:'800'},button:{alignItems:'center',backgroundColor:'#3F72E5',borderRadius:8,bottom:20,height:56,justifyContent:'center',left:16,position:'absolute',right:16},buttonText:{color:'#FFFFFF',fontSize:17,fontWeight:'800'} });
